/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fmod_jni_water_waterfmod_VoiceFixer */

#ifndef _Included_fmod_jni_water_waterfmod_VoiceFixer
#define _Included_fmod_jni_water_waterfmod_VoiceFixer
#ifdef __cplusplus
extern "C" {
#endif
#undef fmod_jni_water_waterfmod_VoiceFixer_MODE_NORMAL
#define fmod_jni_water_waterfmod_VoiceFixer_MODE_NORMAL 0L
#undef fmod_jni_water_waterfmod_VoiceFixer_MODE_LUOLI
#define fmod_jni_water_waterfmod_VoiceFixer_MODE_LUOLI 1L
#undef fmod_jni_water_waterfmod_VoiceFixer_MODE_DASHU
#define fmod_jni_water_waterfmod_VoiceFixer_MODE_DASHU 2L
#undef fmod_jni_water_waterfmod_VoiceFixer_MODE_JINGSONG
#define fmod_jni_water_waterfmod_VoiceFixer_MODE_JINGSONG 3L
#undef fmod_jni_water_waterfmod_VoiceFixer_MODE_GAOGUAI
#define fmod_jni_water_waterfmod_VoiceFixer_MODE_GAOGUAI 4L
#undef fmod_jni_water_waterfmod_VoiceFixer_MODE_KONGLING
#define fmod_jni_water_waterfmod_VoiceFixer_MODE_KONGLING 5L
/*
 * Class:     fmod_jni_water_waterfmod_VoiceFixer
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_fmod_jni_water_waterfmod_VoiceFixer_fix
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
